apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    sonarqube.org/project-key: https://sonarcloud.io/project/overview?id=kjchandan_Backstage-web-Java-code
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: Chandanjslc2001@gmail.com
  lifecycle: experimental
