apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backstage
  description: An example of a Backstage application.
  annotations:
    sonarqube.org/project-key: kjchandan_Backstage-web-Java-code
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
